configfile: "/homes/wsfschuuring/Desktop/DataProcess/SECRET-PROJECT/NewDataProcessProject/config/config.yaml"

include: "rules/create_visual.smk"

rule all:
    input:
        output_png = rules.create_visual.output.barplot_png
