configfile: "/homes/wsfschuuring/Desktop/DataProcess/SECRET-PROJECT/NewDataProcessProject/config/config.yaml"

include: "rules/consensus_calling.smk"

rule all:
    input:
        consensus_file = config["datadir"] + config["R1"] + config["R2"] + "_consensus_sequence.fa"
