datadir: "../NewDataProcessProject/data/"
outputdir: "../NewDataProcessProject/output/"
reference: "../NewDataProcessProject/data/reference.fa"
primers: "../NewDataProcessProject/data/primers.bed"

R1: S-Africa-variant-1_S123_L001_R1_001
R2: S-Africa-variant-1_S123_L001_R2_001
